### ISSUE TITLE
problems using filter option

### ISSUE THREAD

**Issue by samuelgoldenbaum** [borisovg/metalsmith-uglify#18]
I am passing filter as an option; yet seems to be ignored:

```
     .use(uglify({
         filter: ['./lib/lodash/dist/lodash.js']
    }))
```

Can I also process files outside the src folder? This is my structure:

```
-/lib
-/src
--/posts
-/build.js
```

**Comment by ksmithut** [comment]
You could try using globmatching `'**/lib/lodash/dist/lodash.js'` do see if that works.

Metalsmith plugins can only process files that you include in your `.source('./src')`, so if you want it to process other files, be sure it's included in that path.

**Comment by oupala** [comment]
I'm using bootstrap which is imported using npm. Hence my boostrap file are in `node_modules`directory, outside of `src` directory.

Is there a way to concat js file from `node_modules` to the build directory?

For css, the solution was to use `@import` in my `app.scss` file (which is inside my `src` directory) to import scss files from `node_modules`. Is there an equivalent for javascript?

**Comment by ksmithut** [comment]
@oupala It's been a while since I've done much with metalsmith. Are there other plugins that are able to include source files outside of the source directory? If there is, could you send me a link? Then I'll look at how they implement it and see what can be done here.

**Comment by oupala** [comment]
I don't know if the restriction comes from your plugin, or more generally from metalsmith.

There a plugin called [metalsmith-sass](/stevenschobert/metalsmith-sass) that is able to get file from outside the `src` directory. But as **metalsmith-sass** seems to be mainly a wrapper around **sass**, it is maybe sass that has the capability to find files from outside the `src` directory.

We should maybe ask this question in [metalsmith](/segmentio/metalsmith) issue tracker.

**Comment by oupala** [comment]
**metalsmith-copy** has the same problem: it cannot copy files from outside the `src` directory.

**Comment by borisovg** [comment]
In the upcoming v2 release `options.filter` will only accept a function. This should do what you are looking for:

```
{
	filter: function (name) {
		var files = ['lib/lodash/dist/lodash.js'];
		return (files.indexOf(name) !== -1);
	}
}
```

It is not possible to process files outside the source directory, unless you have another plugin that adds them to Metalsmith's files object beforehand.

**Comment by borisovg** [comment]
P.S. the [metalsmith-assets](https://github.com/treygriffith/metalsmith-assets) plugin might be what you are looking for to make this work.

**Comment by oupala** [comment]
@borisovg How would you write a filter function that takes files from multiple directories?

An equivalent of the old filter from metalsmith-uglify v1.x.x:

```js
      filter: [
        'another-dir/**/*.js',
        'js/*.js'
      ],
```

**Comment by borisovg** [comment]
@oupala something like this:

```
function (name) {
	return (name.match(/^(js|another-dir)\/.+\.js$/));
});
```

Regex explanation:
- starts with either "js" or "another-dir", and
- followed by "/", and
- followed by one or more characters, and
- ends in ".js"

**Comment by oupala** [comment]
I'm not sure metalsmith-asset can fit me need. But I asked the question there.

And thanks for the example.

**Comment by oupala** [comment]
What is the link between the filter function and the parameter?

Can we get files from outside the root directory?

In my example, another-dir` would be out of the `js` directory.

**Comment by borisovg** [comment]
Hmm, that's a very good question... The answer is that files outside of root will be excluded and by default root is the directory of the first JS file in the list. Thinking about it now, it doesn't seem like a very good design - will have a think of how to make it better.

**Comment by borisovg** [comment]
OK, I have had some time to look at the code again and it looks like I was saner than I suspected earlier :) The default root (directory of the first JS file in the list) was only for cases of 1:1 minification and was applied later for the purposes of placing the `min.js` file. It did not apply to cases where files were being concatenated which makes total sense.

I made a change to the code so that the custom filter function will have total control over which files are picked. This broke one of the tests but that was specifically for concatenation with a custom filter function so I think this change is OK as it is more inline with the principle of "least surprise". Now, if you provide a filter function, you have to be more explicit.

Please try the change (by downloading https://raw.githubusercontent.com/borisovg/metalsmith-uglify/master/index.js into `node_modules/metalsmith-uglify/`) and let me know if that works better for you and I can publish a new release.

**Comment by oupala** [comment]
It seems to work well @borisovg.

The last problem I have is that bootsrap js is concatenated before jquery. The problem is that bootstrap requires jquery.

And last question: is the `root` parameter still useful when using a `filter` function? If yes, what is it useful for?

**Comment by oupala** [comment]
I find it hard to migration from v1.1.x to version 2.x.x.

Here is my old configuration for version 1.1.x:

```js
     .use(uglify({ // minify and concat javascript
       filter: [
         'node_modules_alias/**/*.js',
         'js/*.js'
       ],
       preserveComments: 'some',
       removeOriginal: true,
       sourceMap: true,
       concat: 'js/app.min.js',
       order: [
         'node_modules_alias/node_modules/jquery/dist/jquery.js', // concat jquery in first
         'node_modules_alias/node_modules/tether/dist/js/tether.js' // then tether in second
       ]
     }))
```

Here is the new one, for version 2.x.x:

```
    .use(uglify({
      filter: function (name) {
	      return (name.match(/^(js|node_modules_alias)\/.+\.js$/));
      },
      concat: {
        file: 'app.min.js',
        root: 'js'
      },
      removeOriginal: true,
      root: './src/',
      uglify: {
        output: {
          comments: 'all'
        }
      }
    }))
```

Almost every parameter have been migrated.

I still have problem with concatenation ordering. The [upgrade documentation](/borisovg/metalsmith-uglify/blob/master/1to2.md) tells me to use `hoist_funs` or to leave uglify do concatenate in the right order, but this does not work. uglify seems to use the alphabetical order to concatenate. Sadly, it was working well with module version 1.1.x.

**Comment by borisovg** [comment]
Run it with `DEBUG=metalsmith-uglify:info:*` and paste the output here (skip the `call_uglify` lines as they will be very verbose - just the `get_js_files`, `main` and `minify` lines).

**Comment by borisovg** [comment]
Also, maybe this will be helpful: I put together a little test scenario for building bootstrap + jquery + custom script.

Bootstrap and jquery are in `node_modules/` outside of `src/` and custom script is `src/js/test.js`.

I use `metalsmith-assets` to pull in the library directories in to a virtual `lib/` directory and then just before building it I ignore it with `metalsmith-ignore`.

Build script:

```
/*jshint node:true*/
'use strict';

var assets = require('metalsmith-assets');
var ignore = require('metalsmith-ignore');
var metalsmith = require('metalsmith');
var uglify = require('metalsmith-uglify');

var jsFiles = [
    'lib/bootstrap/bootstrap.js',
    'lib/jquery/jquery.js',
    'js/test.js'
];

metalsmith(__dirname)
    .source('./src')
    .destination('./public')
    .use(assets({
        source: './node_modules/bootstrap/dist/js',
        destination: './lib/bootstrap'
    }))
    .use(assets({
        source: './node_modules/jquery/dist/',
        destination: './lib/jquery'
    }))
    .use(uglify({
        concat: {
            root: 'js'
        },
        removeOriginal: true,
        filter: function (name) {
            return (jsFiles.indexOf(name) > -1);
        }
    }))
    .use(ignore([
        'lib/**'
    ]))
    .build(function (err) {
        if (err) {
            console.error('Build Failed:', err);
        } else {
            console.log('Build Finished');
        }
    });
```

Debug output:
```
  metalsmith-uglify:info:get_js_files Root: js/ +0ms
  metalsmith-uglify:info:main Options: { concat: { root: 'js' },
  metalsmith-uglify:info:main   removeOriginal: true,
  metalsmith-uglify:info:main   filter: [Function: filter],
  metalsmith-uglify:info:main   uglify: { sourceMap: { includeSources: true } } } +0ms
  metalsmith-uglify:info:main JS Files: [ 'js/test.js',
  metalsmith-uglify:info:main   'lib/bootstrap/bootstrap.js',
  metalsmith-uglify:info:main   'lib/jquery/jquery.js' ] +1ms
  metalsmith-uglify:info:main Processing Started +1ms
  metalsmith-uglify:info:minify pathMin: js/scripts.min.js +0ms
  metalsmith-uglify:info:minify Removed: js/test.js +2s
  metalsmith-uglify:info:minify Removed: lib/bootstrap/bootstrap.js +1ms
  metalsmith-uglify:info:minify Removed: lib/jquery/jquery.js +0ms
  metalsmith-uglify:info:main Processing Finished +2s
```

**Comment by borisovg** [comment]
And to answer your other question: yes `root` is still useful with a custom filter, especially when concatenating files, because it determines where the bundle file will be placed (see pathMin in the debug output). It is clearer to use `concat.root` in this case, although both will work.

If no root is specified then it will be guessed from the directory of the first file in the list, which is fine for 1:1 minification but will probably cause unexpected behaviour when concatenating multiple files.

**Comment by oupala** [comment]
Here is the output of my debug:

```log
  metalsmith-uglify:info:get_js_files Root: js/ +0ms
  metalsmith-uglify:info:main Options: { filter: [Function: filter],
  metalsmith-uglify:info:main   concat: { file: 'app.min.js', root: 'js' },
  metalsmith-uglify:info:main   removeOriginal: true,
  metalsmith-uglify:info:main   uglify: 
  metalsmith-uglify:info:main    { output: { comments: 'all' },
  metalsmith-uglify:info:main      sourceMap: { includeSources: true } } } +0ms
  metalsmith-uglify:info:main JS Files: [ 'js/app.js',
  metalsmith-uglify:info:main   'node_modules_alias/node_modules/jquery/dist/jquery.js',
  metalsmith-uglify:info:main   'node_modules_alias/node_modules/highlight.js/lib/highlight.js',
  metalsmith-uglify:info:main   'node_modules_alias/node_modules/boosted/dist/js/boosted.js',
  metalsmith-uglify:info:main   'node_modules_alias/node_modules/tether/dist/js/tether.js' ] +1ms
  metalsmith-uglify:info:main Processing Started +0ms
  metalsmith-uglify:info:minify pathMin: js/app.min.js +0ms
  metalsmith-uglify:info:call_uglify Result: { code: '" [lots of js]' "]}}
  metalsmith-uglify:info:minify Removed: js/app.js +3s
  metalsmith-uglify:info:minify Removed: node_modules_alias/node_modules/jquery/dist/jquery.js +1ms
  metalsmith-uglify:info:minify Removed: node_modules_alias/node_modules/highlight.js/lib/highlight.js +0ms
  metalsmith-uglify:info:minify Removed: node_modules_alias/node_modules/boosted/dist/js/boosted.js +0ms
  metalsmith-uglify:info:minify Removed: node_modules_alias/node_modules/tether/dist/js/tether.js +0ms
  metalsmith-uglify:info:main Processing Finished +3s
```

**Comment by borisovg** [comment]
jQuery sucks - because they do a funny dance before they declare `$`, UglifyJS doesn't automagically parse it in the right way, so it seems you have to play the "files in a certain order" game to get it to work.

So I added another option: `files`, which works like the old `filter` except that it has to be an array of files.  Try downloading https://raw.githubusercontent.com/borisovg/metalsmith-uglify/master/index.js again, replace `filter` with `files` and hopefully it finally works for you (I tested it with those files and it seems to work, at least for loading jQuery).

```
        files: [
            'lib/jquery/jquery.js',
            'lib/boosted/boosted.js',
            'lib/highlight.js/highlight.js',
            'lib/tether/tether.js'
        ]
```

**Comment by oupala** [comment]
This works for me.

But if you have a look at [this comment](/borisovg/metalsmith-uglify/issues/18#issuecomment-370377683), you can see that the old 1.1.x config version has two parameters: `filter` and `order`.

```js
     .use(uglify({ // minify and concat javascript
       filter: [
         'node_modules_alias/**/*.js',
         'js/*.js'
       ],
       preserveComments: 'some',
       removeOriginal: true,
       sourceMap: true,
       concat: 'js/app.min.js',
       order: [
         'node_modules_alias/node_modules/jquery/dist/jquery.js', // concat jquery in first
         'node_modules_alias/node_modules/tether/dist/js/tether.js' // then tether in second
       ]
     }))
```

`filter` lists all the resources that need to be minified and concatenated, while `order` tell what resources to concatenate first. And all non listed resources in `order` are minified and concatenated after.

The good thing about this solution is that the `filter` parameter accepts wildcard.

I did not knew about this jQuery *funny dance*. Do you have some more information about that?

**Comment by borisovg** [comment]
> The good thing about this solution is that the filter parameter accepts wildcards

It is not a good thing: if you had aliased the `jquery/dist/` directory in then that wildcard would bring in `core.js`, ` jquery.js` and `jquery.slim.js`. So now you have to filter more explicitly and you might as well just write an explicit list (i.e. the `files` option). Or, if you are bundling sanely written JS, then you can just bring in your dependencies into `src/js` (e.g. with a symlink) and bundle the lot with the default settings. The `files` option is just a last-ditch workaround.

> I did not knew about this jQuery funny dance. Do you have some more information about that?

Look at the bottom of `dist/jquery.js` - it is truly code from a different age...

**Comment by oupala** [comment]
Ok, that make sense. Do you plan to release this version?

**Comment by oupala** [comment]
Oops, you seem to have done that already.
