### ISSUE TITLE
 New dependency name: uglify-es => terser #1 

### ISSUE THREAD

**Issue by fabiosantoscode** [borisovg/metalsmith-uglify#21]
There has been development on a new fork of uglify-es, which is now called terser and has its own package!

    "terser": "^3.7.3"

Please upgrade to our new version.

**Comment by borisovg** [comment]
@fabiosantoscode is it backwards compatible (for semver purposes)?

**Comment by fabiosantoscode** [comment]
Yes. We haven't incremented the major or published any breaking changes!

**Comment by borisovg** [comment]
Let me know when you have resolved your ghost package maintainer issue (terser#2)

**Comment by fabiosantoscode** [comment]
@borisovg the issue has been resolved
